version: "3.1"

services:
  Redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    networks:
      redeInterna:
        ipv4_address: 172.16.238.12
        ipv6_address: "2001:3984:3989::12"

networks:
  redeInterna:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
        - subnet: "2001:3984:3989::/64"
          gateway: "2001:3984:3989::1"

